map_type: costmap

obstacle_range: 1.0 #3.0
raytrace_range: 1.0 #3.0

transform_tolerance:  0.2

robot_radius: 0.1
inflation_radius: 0.5 #0.35
cost_scaling_factor: 15

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
